package com.dailyhealthcoach.domain.model

data class FoodEntryInput(
    val id: Long = 0,
    val date: String,
    val mealName: String,
    val foodName: String,
    val brandName: String?,
    val servingDescription: String?,
    val quantity: Double = 1.0,
    val calories: Int?,
    val proteinGrams: Double?,
    val carbGrams: Double?,
    val fatGrams: Double?,
    val fiberGrams: Double?,
    val mealTime: String?,
    val isWholeFoodBased: Boolean,
    val isProcessed: Boolean,
    val isFermented: Boolean,
    val barcode: String? = null,
    val source: String = "MANUAL",
    val vitaminA: Double? = null,
    val vitaminC: Double? = null,
    val vitaminD: Double? = null,
    val vitaminB12: Double? = null,
    val calcium: Double? = null,
    val iron: Double? = null,
    val potassium: Double? = null,
    val magnesium: Double? = null,
    val sodium: Double? = null,
    val zinc: Double? = null,
    val vitaminE: Double? = null,
    val vitaminK: Double? = null,
    val vitaminB1: Double? = null,
    val vitaminB2: Double? = null,
    val vitaminB3: Double? = null,
    val vitaminB6: Double? = null,
    val folate: Double? = null,
    val biotin: Double? = null,
    val pantothenicAcid: Double? = null,
    val phosphorus: Double? = null,
    val iodine: Double? = null,
    val selenium: Double? = null,
    val copper: Double? = null,
    val manganese: Double? = null,
    val chromium: Double? = null,
    val molybdenum: Double? = null
)
