package com.dailyhealthcoach.ui.nutrition

data class NutritionUiState(
    val calories: Int = 0,
    val proteinGrams: Double = 0.0,
    val carbGrams: Double = 0.0,
    val fatGrams: Double = 0.0,
    val fiberGrams: Double = 0.0,
    val proteinGoalMin: Int = 170,
    val proteinGoalMax: Int = 200,
    val calorieTarget: Int = 2000,
    val carbGoal: Int = 0,
    val fatGoal: Int = 0,
    val fiberGoal: Int = 0,
    val latestMealTime: String = "Not logged",
    val mealSections: List<MealSectionUiState> = emptyList(),
    val isFormVisible: Boolean = false,
    val form: FoodEntryFormUiState = FoodEntryFormUiState(),
    val recentFoods: List<QuickAddFoodUiState> = emptyList(),
    val savedFoods: List<QuickAddFoodUiState> = emptyList(),
    val usualMeals: List<UsualMealUiState> = emptyList(),
    val isScannerVisible: Boolean = false,
    val isLabelScannerVisible: Boolean = false,
    val barcodeMessage: String? = null,
    val labelScanMessage: String? = null,
    val ocrConfirmMessage: String? = null,
    val isAiLogVisible: Boolean = false,
    val aiInput: String = "",
    val isAiParsing: Boolean = false,
    val aiConfidenceMessage: String? = null,
    val quickAddDialogFood: QuickAddFoodUiState? = null,
    val quickAddMealName: String = "",
    val quickAddQuantity: String = "1",
    val quickAddTime: String = "",
    val suggestions: List<RecipeSuggestionUiState> = emptyList(),
    val todayPlanMeals: List<RecipeSuggestionUiState> = emptyList()
)

data class RecipeSuggestionUiState(
    val mealName: String,
    val food: QuickAddFoodUiState
)

data class UsualMealUiState(
    val foodName: String,
    val brandName: String?,
    val servingDescription: String?,
    val mealName: String,
    val calories: Int,
    val proteinGrams: Double,
    val carbGrams: Double,
    val fatGrams: Double,
    val fiberGrams: Double,
    val timesLogged: Int,
    val loggedToday: Boolean,
    val isWholeFoodBased: Boolean,
    val isProcessed: Boolean,
    val isFermented: Boolean
)

data class QuickAddFoodUiState(
    val sourceEntryId: Long,
    val foodName: String,
    val brandName: String?,
    val servingDescription: String?,
    val calories: Int,
    val proteinGrams: Double,
    val carbGrams: Double,
    val fatGrams: Double,
    val fiberGrams: Double,
    val defaultMealName: String,
    val isSaved: Boolean,
    val isWholeFoodBased: Boolean,
    val isProcessed: Boolean,
    val isFermented: Boolean,
    val barcode: String? = null,
    val source: String = "MANUAL",
    val vitaminA: Double? = null,
    val vitaminC: Double? = null,
    val vitaminD: Double? = null,
    val vitaminB12: Double? = null,
    val calcium: Double? = null,
    val iron: Double? = null,
    val potassium: Double? = null,
    val magnesium: Double? = null,
    val sodium: Double? = null,
    val zinc: Double? = null,
    val vitaminE: Double? = null,
    val vitaminK: Double? = null,
    val vitaminB1: Double? = null,
    val vitaminB2: Double? = null,
    val vitaminB3: Double? = null,
    val vitaminB6: Double? = null,
    val folate: Double? = null,
    val biotin: Double? = null,
    val pantothenicAcid: Double? = null,
    val phosphorus: Double? = null,
    val iodine: Double? = null,
    val selenium: Double? = null,
    val copper: Double? = null,
    val manganese: Double? = null,
    val chromium: Double? = null,
    val molybdenum: Double? = null
)

data class MealSectionUiState(
    val mealName: String,
    val entries: List<FoodEntryUiState>
)

data class FoodEntryUiState(
    val id: Long,
    val mealName: String,
    val foodName: String,
    val brandName: String?,
    val servingDescription: String?,
    val quantity: Double = 1.0,
    val calories: Int,
    val proteinGrams: Double,
    val carbGrams: Double,
    val fatGrams: Double,
    val fiberGrams: Double,
    val mealTime: String?,
    val isWholeFoodBased: Boolean,
    val isProcessed: Boolean,
    val isFermented: Boolean,
    val isSaved: Boolean = false,
    val barcode: String? = null,
    val source: String = "MANUAL",
    val vitaminA: Double? = null,
    val vitaminC: Double? = null,
    val vitaminD: Double? = null,
    val vitaminB12: Double? = null,
    val calcium: Double? = null,
    val iron: Double? = null,
    val potassium: Double? = null,
    val magnesium: Double? = null,
    val sodium: Double? = null,
    val zinc: Double? = null,
    val vitaminE: Double? = null,
    val vitaminK: Double? = null,
    val vitaminB1: Double? = null,
    val vitaminB2: Double? = null,
    val vitaminB3: Double? = null,
    val vitaminB6: Double? = null,
    val folate: Double? = null,
    val biotin: Double? = null,
    val pantothenicAcid: Double? = null,
    val phosphorus: Double? = null,
    val iodine: Double? = null,
    val selenium: Double? = null,
    val copper: Double? = null,
    val manganese: Double? = null,
    val chromium: Double? = null,
    val molybdenum: Double? = null
)

data class FoodEntryFormUiState(
    val editingId: Long = 0,
    val mealName: String = "Breakfast",
    val foodName: String = "",
    val brandName: String = "",
    val servingDescription: String = "",
    val quantity: String = "1",
    val calories: String = "",
    val proteinGrams: String = "",
    val carbGrams: String = "",
    val fatGrams: String = "",
    val fiberGrams: String = "",
    val mealTime: String = "",
    val isWholeFoodBased: Boolean = true,
    val isProcessed: Boolean = false,
    val isFermented: Boolean = false,
    val barcode: String = "",
    val source: String = "MANUAL",
    val vitaminA: String = "",
    val vitaminC: String = "",
    val vitaminD: String = "",
    val vitaminB12: String = "",
    val calcium: String = "",
    val iron: String = "",
    val potassium: String = "",
    val magnesium: String = "",
    val sodium: String = "",
    val zinc: String = "",
    val vitaminE: String = "",
    val vitaminK: String = "",
    val vitaminB1: String = "",
    val vitaminB2: String = "",
    val vitaminB3: String = "",
    val vitaminB6: String = "",
    val folate: String = "",
    val biotin: String = "",
    val pantothenicAcid: String = "",
    val phosphorus: String = "",
    val iodine: String = "",
    val selenium: String = "",
    val copper: String = "",
    val manganese: String = "",
    val chromium: String = "",
    val molybdenum: String = ""
)
