package com.dailyhealthcoach.ui.recipes.catalog

import com.dailyhealthcoach.ui.recipes.Recipe

object DinnerRecipes2 {
    val ALL: List<Recipe> = listOf(

        Recipe(
            id = "paneer_tikka_masala",
            name = "Paneer Tikka Masala",
            description = "The definitive Indian restaurant classic — grilled paneer tikka simmered in a rich, spiced tomato-cream gravy — made lighter with fat-free yogurt and a moderate amount of cream. A 40 g protein dinner with complex, layered flavours that genuinely rewards the effort.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Paneer",
            restrictions = listOf("Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "200g paneer (cubed)",
                "3 tbsp fat-free yogurt (marinade)",
                "1 tsp tikka masala spice blend (or ½ tsp each cumin + coriander + ¼ tsp chilli)",
                "2 medium tomatoes (blended)",
                "1 small onion (finely diced)",
                "1 tsp ginger-garlic paste",
                "1 tsp cumin seeds",
                "¼ tsp turmeric",
                "¼ tsp garam masala",
                "2 tbsp low-fat cream or cashew cream",
                "1 tsp oil",
                "Salt to taste",
                "Fresh coriander to garnish"
            ),
            calories = 500, proteinGrams = 40.0, carbGrams = 18.0, fatGrams = 30.0, fiberGrams = 3.0,
            prepMinutes = 15, cookMinutes = 25,
            instructions = listOf(
                "Marinate paneer in yogurt and tikka spice blend for 15 minutes.",
                "Grill marinated paneer in a dry non-stick pan 3–4 minutes per side until charred; set aside.",
                "Heat oil; add cumin seeds; add onion and cook 5 minutes until golden.",
                "Add ginger-garlic paste and cook 1 minute; add blended tomato and turmeric.",
                "Cook gravy 10 minutes until thick and oil separates.",
                "Add grilled paneer; stir in cream; simmer 5 minutes.",
                "Finish with garam masala and coriander."
            ),
            metabolicResetScore = 8,
            antiInflammatoryScore = 5,
            insulinResistanceScore = 8,
            womensHealthScore = 6,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "tempeh_stir_fry_bowl",
            name = "Ginger Tempeh & Vegetable Stir-Fry",
            description = "Sliced tempeh flash-fried with broccoli, snap peas, bell pepper, and a bold ginger-tamari sauce. A 34 g plant-protein dinner ready in 20 minutes with an antiInflammatoryScore of 9.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Soy",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "200g tempeh (sliced into strips)",
                "1 cup broccoli florets",
                "½ cup snap peas",
                "½ red bell pepper (sliced)",
                "2 garlic cloves (minced)",
                "1 tbsp fresh ginger (grated)",
                "2 tbsp tamari (or soy sauce)",
                "1 tsp sesame oil",
                "1 tsp rice vinegar",
                "½ tsp chilli flakes",
                "1 tsp oil for cooking",
                "½ cup cooked brown rice (to serve)",
                "1 tbsp sesame seeds (garnish)"
            ),
            calories = 480, proteinGrams = 34.0, carbGrams = 42.0, fatGrams = 18.0, fiberGrams = 8.0,
            prepMinutes = 10, cookMinutes = 15,
            instructions = listOf(
                "Mix tamari, sesame oil, rice vinegar, and chilli flakes to make sauce.",
                "Heat oil in a wok or large pan over high heat; fry tempeh strips 3 minutes per side until golden.",
                "Push tempeh to the side; add garlic and ginger and cook 30 seconds.",
                "Add broccoli, snap peas, and pepper; stir-fry 4–5 minutes on high heat.",
                "Pour sauce over everything and toss 1 minute.",
                "Serve over brown rice; garnish with sesame seeds."
            ),
            metabolicResetScore = 7,
            antiInflammatoryScore = 9,
            insulinResistanceScore = 7,
            womensHealthScore = 9,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "black_bean_cottage_bowl",
            name = "Black Bean, Quinoa & Cottage Cheese Bowl",
            description = "A warming bowl of black beans simmered in cumin and lime served over quinoa with a dollop of cold cottage cheese that melts into a protein-rich sauce. The three-protein combination of legume, grain, and dairy pushes this to 38 g total protein.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Cottage Cheese",
            restrictions = listOf("Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "1 can black beans (400g, drained and rinsed)",
                "½ cup dry quinoa (rinsed, cooked)",
                "½ cup low-fat cottage cheese",
                "1 small onion (diced)",
                "2 garlic cloves (minced)",
                "½ tsp cumin",
                "¼ tsp smoked paprika",
                "1 tsp olive oil",
                "1 tbsp lime juice",
                "Salt and pepper to taste",
                "Fresh coriander (optional)"
            ),
            calories = 490, proteinGrams = 38.0, carbGrams = 68.0, fatGrams = 8.0, fiberGrams = 14.0,
            prepMinutes = 8, cookMinutes = 18,
            instructions = listOf(
                "Cook quinoa in 1 cup water 14 minutes; set aside.",
                "Heat oil; sauté onion 4 minutes; add garlic, cumin, and paprika and cook 1 minute.",
                "Add black beans and ¼ cup water; simmer 8 minutes; mash slightly to thicken.",
                "Stir in lime juice and season.",
                "Serve black beans over quinoa; top with cold cottage cheese; garnish with coriander."
            ),
            metabolicResetScore = 9,
            antiInflammatoryScore = 7,
            insulinResistanceScore = 9,
            womensHealthScore = 8,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "moong_sprout_sabzi_bowl",
            name = "Moong Sprout Sabzi with Roti",
            description = "A dry Indian stir-fry of sprouted moong beans with tomato, ginger, and spices served alongside a single whole-wheat roti. Sprouting boosts the protein bioavailability and dramatically reduces the glucoseImpactScore versus cooked whole lentils.",
            mealType = "Dinner",
            tags = listOf("Vegan", "Whole Foods"),
            proteinSource = "Lentils",
            restrictions = listOf("Dairy Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "1½ cups sprouted moong beans (or canned, drained)",
                "1 medium tomato (chopped)",
                "1 small onion (finely diced)",
                "1 tsp ginger (grated)",
                "½ tsp mustard seeds",
                "½ tsp cumin",
                "¼ tsp turmeric",
                "¼ tsp coriander powder",
                "1 tsp oil",
                "Salt to taste",
                "1 tbsp lemon juice",
                "1 whole-wheat roti (to serve)"
            ),
            calories = 380, proteinGrams = 28.0, carbGrams = 56.0, fatGrams = 5.0, fiberGrams = 11.0,
            prepMinutes = 5, cookMinutes = 15,
            instructions = listOf(
                "Heat oil; add mustard seeds and let them splutter; add cumin.",
                "Add onion and cook 4 minutes; add ginger and cook 1 minute.",
                "Add tomato, turmeric, coriander, and salt; cook 4 minutes until tomato softens.",
                "Add sprouted moong; toss and cook 5 minutes on medium heat.",
                "Finish with lemon juice; serve with roti."
            ),
            metabolicResetScore = 9,
            antiInflammatoryScore = 7,
            insulinResistanceScore = 9,
            womensHealthScore = 8,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "baked_tofu_miso_eggplant",
            name = "Baked Miso Tofu with Roasted Eggplant",
            description = "Firm tofu glazed in white miso and baked alongside sliced Japanese eggplant until caramelised. A 30 g plant-protein dinner with exceptional umami depth and one of the highest antiInflammatoryScores in the plan.",
            mealType = "Dinner",
            tags = listOf("Vegan"),
            proteinSource = "Tofu",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "300g extra-firm tofu (pressed, sliced into planks)",
                "1 large eggplant (sliced into rounds)",
                "2 tbsp white miso paste",
                "1 tbsp tamari",
                "1 tsp sesame oil",
                "1 tsp rice vinegar",
                "1 tsp grated fresh ginger",
                "½ cup cooked brown rice (to serve)",
                "1 spring onion (sliced, garnish)",
                "Sesame seeds (garnish)"
            ),
            calories = 420, proteinGrams = 30.0, carbGrams = 42.0, fatGrams = 14.0, fiberGrams = 8.0,
            prepMinutes = 10, cookMinutes = 30,
            instructions = listOf(
                "Preheat oven to 200°C. Whisk miso, tamari, sesame oil, rice vinegar, and ginger.",
                "Brush tofu planks generously with miso glaze; place on a lined baking tray.",
                "Toss eggplant slices with remaining glaze; arrange on the same tray.",
                "Bake 25–30 minutes, turning tofu once, until deeply golden.",
                "Serve over brown rice; garnish with spring onion and sesame seeds."
            ),
            metabolicResetScore = 6,
            antiInflammatoryScore = 9,
            insulinResistanceScore = 6,
            womensHealthScore = 9,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "soya_chunk_curry",
            name = "Soya Chunk Masala Curry",
            description = "Rehydrated soya chunks simmered in a rich, aromatic tomato masala — one of the most economical high-protein dinners available. At 44 g of plant protein and an insulinResistanceScore of 9, this is the top protein-to-insulin-load meal in the entire dinner catalog.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Soy",
            restrictions = listOf("Dairy Free", "Nut Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "100g dry soya chunks (rehydrated: soak in hot water 15 min, squeeze dry)",
                "2 medium tomatoes (blended)",
                "1 medium onion (finely diced)",
                "1 tsp ginger-garlic paste",
                "1 tsp cumin seeds",
                "½ tsp coriander powder",
                "¼ tsp turmeric",
                "¼ tsp chilli powder",
                "¼ tsp garam masala",
                "1 tsp oil",
                "Salt to taste",
                "Fresh coriander to garnish"
            ),
            calories = 380, proteinGrams = 44.0, carbGrams = 22.0, fatGrams = 7.0, fiberGrams = 6.0,
            prepMinutes = 15, cookMinutes = 20,
            instructions = listOf(
                "Soak soya chunks in hot water 15 minutes; squeeze thoroughly to remove excess water.",
                "Heat oil; add cumin; add onion and cook 6 minutes until golden.",
                "Add ginger-garlic paste and cook 1 minute; add blended tomato.",
                "Cook tomato gravy 8–10 minutes until thick and oil separates; add all dry spices.",
                "Add squeezed soya chunks; stir to coat; simmer 8 minutes.",
                "Finish with garam masala and coriander."
            ),
            metabolicResetScore = 9,
            antiInflammatoryScore = 6,
            insulinResistanceScore = 9,
            womensHealthScore = 7,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "lentil_shepherd_pie",
            name = "Red Lentil Shepherd's Pie",
            description = "A plant-based shepherd's pie with a spiced red lentil and vegetable filling topped with smooth cauliflower mash instead of potato. The cauliflower top cuts the glucoseImpactScore to 3 while keeping the comforting, hearty character of the dish intact.",
            mealType = "Dinner",
            tags = listOf("Vegan", "Whole Foods"),
            proteinSource = "Lentils",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "1 cup red lentils (rinsed)",
                "1 medium carrot (diced)",
                "½ cup frozen peas",
                "1 small onion (diced)",
                "2 garlic cloves (minced)",
                "1 can chopped tomatoes (400g)",
                "1 tsp cumin",
                "½ tsp smoked paprika",
                "1 tsp olive oil",
                "Salt and pepper to taste",
                "Cauliflower mash: 1 small cauliflower (600g), 2 tbsp olive oil, salt"
            ),
            calories = 460, proteinGrams = 30.0, carbGrams = 58.0, fatGrams = 9.0, fiberGrams = 16.0,
            prepMinutes = 15, cookMinutes = 40,
            instructions = listOf(
                "Cauliflower mash: steam cauliflower until very tender; blend with olive oil and salt until smooth.",
                "Heat oil; sauté onion and garlic 4 minutes; add carrot and cook 3 minutes.",
                "Add lentils, canned tomatoes, 1 cup water, cumin, paprika, salt, and pepper.",
                "Simmer 20 minutes until lentils are soft; stir in peas.",
                "Transfer to a baking dish; top with cauliflower mash; bake at 190°C for 15 minutes.",
                "Broil 2 minutes for a golden top."
            ),
            storageNotes = "Excellent for batch cooking — refrigerates 4 days, freezes 3 months.",
            metabolicResetScore = 9,
            antiInflammatoryScore = 7,
            insulinResistanceScore = 9,
            womensHealthScore = 8,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "greek_yogurt_stuffed_peppers",
            name = "Greek Yogurt Stuffed Bell Peppers",
            description = "Red bell peppers filled with a protein-dense mixture of quinoa, chickpeas, and herbed Greek yogurt, then baked until tender. A 36 g protein dinner with genuine visual appeal and a complete amino acid profile from three complementary proteins.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Greek Yogurt",
            restrictions = listOf("Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "3 large red bell peppers (halved, deseeded)",
                "½ cup dry quinoa (cooked)",
                "½ can chickpeas (200g, drained)",
                "¾ cup non-fat Greek yogurt",
                "1 garlic clove (minced)",
                "½ tsp cumin",
                "¼ tsp smoked paprika",
                "1 tbsp lemon juice",
                "2 tbsp fresh parsley",
                "Salt and pepper to taste"
            ),
            calories = 450, proteinGrams = 36.0, carbGrams = 52.0, fatGrams = 6.0, fiberGrams = 9.0,
            prepMinutes = 12, cookMinutes = 25,
            instructions = listOf(
                "Cook quinoa; allow to cool 5 minutes.",
                "Mix quinoa, chickpeas, Greek yogurt, garlic, cumin, paprika, lemon juice, parsley, salt, and pepper.",
                "Arrange pepper halves cut-side up in a baking dish; fill generously.",
                "Bake at 190°C for 20–25 minutes until peppers are tender.",
                "Serve immediately."
            ),
            metabolicResetScore = 8,
            antiInflammatoryScore = 6,
            insulinResistanceScore = 8,
            womensHealthScore = 8,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "saag_paneer",
            name = "Saag Paneer",
            description = "A classic Punjabi dish of silky puréed spinach and mustard greens with pan-fried paneer cubes in a ginger-forward masala. The spinach base makes this one of the most nutrient-dense dinners in the plan — exceptionally high in iron, calcium, folate, and antioxidants alongside 40 g of protein.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Paneer",
            restrictions = listOf("Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "200g paneer (cubed and lightly fried)",
                "300g fresh spinach (or 200g spinach + 100g mustard leaves)",
                "1 medium onion (finely diced)",
                "1 tsp ginger (grated)",
                "2 garlic cloves (minced)",
                "1 green chilli (optional)",
                "½ tsp cumin seeds",
                "¼ tsp turmeric",
                "¼ tsp garam masala",
                "1 tbsp fat-free yogurt",
                "1 tsp ghee or oil",
                "Salt to taste"
            ),
            calories = 470, proteinGrams = 40.0, carbGrams = 14.0, fatGrams = 28.0, fiberGrams = 5.0,
            prepMinutes = 10, cookMinutes = 25,
            instructions = listOf(
                "Blanch spinach (and mustard leaves) 2 minutes; drain and blend to a coarse purée.",
                "Lightly fry paneer cubes in a dry pan until golden; set aside.",
                "Heat ghee; add cumin; add onion and cook 5 minutes until golden.",
                "Add ginger, garlic, and chilli; cook 1 minute.",
                "Add spinach purée, turmeric, and salt; simmer 8 minutes.",
                "Stir in yogurt; add paneer; simmer 5 minutes.",
                "Finish with garam masala."
            ),
            metabolicResetScore = 7,
            antiInflammatoryScore = 8,
            insulinResistanceScore = 8,
            womensHealthScore = 9,
            glucoseImpactScore = 2
        ),

        Recipe(
            id = "masoor_dal_egg_bowl",
            name = "Red Masoor Dal with Poached Eggs",
            description = "Velvety red masoor dal — the fastest-cooking lentil — topped with two soft-poached eggs in the North African shakshuka tradition. The egg-and-lentil pairing is one of the most protein-complete combinations in the plan at 38 g of mixed protein.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Eggs",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Soy Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "¾ cup red masoor dal (rinsed)",
                "2 whole eggs",
                "1 medium tomato (chopped)",
                "1 small onion (diced)",
                "1 garlic clove (minced)",
                "½ tsp cumin seeds",
                "¼ tsp turmeric",
                "¼ tsp coriander powder",
                "¼ tsp garam masala",
                "1 tsp oil",
                "Salt and chilli to taste",
                "Fresh coriander to garnish"
            ),
            calories = 430, proteinGrams = 38.0, carbGrams = 48.0, fatGrams = 13.0, fiberGrams = 11.0,
            prepMinutes = 5, cookMinutes = 22,
            instructions = listOf(
                "Simmer dal in 2 cups water with turmeric and salt for 18 minutes until soft.",
                "In a separate pan heat oil; add cumin; add onion and cook 4 minutes.",
                "Add garlic, tomato, coriander powder, and salt; cook 5 minutes.",
                "Stir tomato masala into cooked dal; bring to a simmer.",
                "Make two small wells in the dal; crack an egg into each.",
                "Cover and cook on low heat 4–5 minutes until egg whites are set.",
                "Finish with garam masala and coriander."
            ),
            metabolicResetScore = 9,
            antiInflammatoryScore = 6,
            insulinResistanceScore = 9,
            womensHealthScore = 7,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "chickpea_spinach_curry",
            name = "Chickpea & Spinach Curry",
            description = "A deeply spiced, entirely plant-based curry of chickpeas and baby spinach in a thick tomato-onion masala. Exceptionally high in fibre and iron, with 30 g of plant protein and an insulinResistanceScore of 9 — one of the best plant-based dinner options for blood sugar control.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein", "Whole Foods"),
            proteinSource = "Lentils",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset", "Anti-Inflammatory"),
            ingredients = listOf(
                "2 cans chickpeas (800g, drained and rinsed)",
                "200g baby spinach",
                "2 medium tomatoes (blended)",
                "1 medium onion (finely diced)",
                "1 tsp ginger-garlic paste",
                "1 tsp cumin seeds",
                "1 tsp coriander powder",
                "½ tsp turmeric",
                "½ tsp garam masala",
                "¼ tsp chilli powder",
                "1 tsp oil",
                "Salt to taste"
            ),
            calories = 450, proteinGrams = 30.0, carbGrams = 62.0, fatGrams = 8.0, fiberGrams = 16.0,
            prepMinutes = 8, cookMinutes = 22,
            instructions = listOf(
                "Heat oil; add cumin seeds; add onion and cook 6 minutes until golden.",
                "Add ginger-garlic paste and cook 1 minute; add blended tomato.",
                "Cook gravy 8 minutes until thick; add turmeric, coriander, and chilli.",
                "Add chickpeas and ½ cup water; simmer 8 minutes.",
                "Stir in spinach and cook 2 minutes until wilted.",
                "Finish with garam masala and salt."
            ),
            storageNotes = "Improves overnight. Refrigerates 4 days; freezes 3 months.",
            metabolicResetScore = 9,
            antiInflammatoryScore = 8,
            insulinResistanceScore = 9,
            womensHealthScore = 8,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "high_protein_veggie_omelette",
            name = "Protein-Dense Vegetable Omelette",
            description = "A thick, golden omelette made with whole eggs and egg whites, loaded with spinach, onion, and tomato, and finished with grated paneer stirred into the egg mixture for additional protein. At 40 g protein and a glucoseImpactScore of 1, this is the most insulin-friendly dinner in the plan.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Eggs",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Soy Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "3 whole eggs",
                "4 egg whites",
                "50g paneer (finely grated)",
                "1 cup baby spinach (chopped)",
                "¼ small onion (finely diced)",
                "¼ medium tomato (finely diced, seeds removed)",
                "1 green chilli (minced, optional)",
                "¼ tsp turmeric",
                "¼ tsp black pepper",
                "½ tsp oil",
                "Salt to taste"
            ),
            calories = 390, proteinGrams = 40.0, carbGrams = 8.0, fatGrams = 22.0, fiberGrams = 2.0,
            prepMinutes = 5, cookMinutes = 12,
            instructions = listOf(
                "Whisk whole eggs, egg whites, turmeric, pepper, and salt until well combined.",
                "Stir grated paneer, spinach, onion, tomato, and chilli into the egg mixture.",
                "Heat a non-stick pan over medium heat; add oil.",
                "Pour egg mixture into pan; spread level; cook covered on low heat 6–7 minutes.",
                "Carefully flip; cook uncovered 3–4 minutes until second side is golden.",
                "Slide onto a plate; slice and serve immediately."
            ),
            metabolicResetScore = 9,
            antiInflammatoryScore = 5,
            insulinResistanceScore = 9,
            womensHealthScore = 7,
            glucoseImpactScore = 1
        ),
    )
}
