package com.dailyhealthcoach.ui.recipes.catalog

import com.dailyhealthcoach.ui.recipes.Recipe

object DinnerRecipes {
    val ALL: List<Recipe> = listOf(

        Recipe(
            id = "tofu_stir_fry",
            name = "Tofu & Broccoli Stir-Fry Bowl",
            description = "Crispy tofu and broccoli tossed in a ginger-garlic soy sauce over brown rice. Ginger and garlic are proven anti-inflammatory agents; broccoli provides sulforaphane.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Tofu",
            restrictions = listOf("Dairy Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "200g firm tofu (pressed, cubed)",
                "2 cups broccoli florets",
                "½ cup snap peas",
                "½ cup cooked brown rice",
                "2 tbsp low-sodium soy sauce",
                "1 tbsp sesame oil",
                "1 tsp fresh ginger (grated)",
                "2 garlic cloves (minced)",
                "1 tsp cornstarch"
            ),
            calories = 420, proteinGrams = 26.0, carbGrams = 44.0, fatGrams = 14.0, fiberGrams = 7.0,
            prepMinutes = 15, cookMinutes = 15,
            instructions = listOf(
                "Press tofu dry; toss with cornstarch and a pinch of salt.",
                "Pan-fry in sesame oil over high heat until golden, about 5 minutes; set aside.",
                "In the same pan, sauté garlic and ginger 1 minute.",
                "Add broccoli and snap peas; stir-fry 4 minutes.",
                "Return tofu; add soy sauce, toss to coat. Serve over brown rice."
            ),
            metabolicResetScore = 5,
            antiInflammatoryScore = 9,
            insulinResistanceScore = 6,
            womensHealthScore = 7,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "lentil_rice_bowl",
            name = "Turmeric Lentil & Basmati Rice Bowl",
            description = "Comforting khichdi-style bowl of red lentils and basmati rice simmered with turmeric and cumin. Turmeric's curcumin is one of the most studied anti-inflammatory compounds.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein", "Whole Foods"),
            proteinSource = "Lentils",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset", "Anti-Inflammatory"),
            ingredients = listOf(
                "½ cup red lentils (rinsed)",
                "½ cup basmati rice",
                "1½ cups vegetable broth",
                "1 tsp cumin seeds",
                "1 tsp turmeric",
                "2 garlic cloves (minced)",
                "1 tbsp olive oil",
                "Salt and pepper to taste",
                "Lemon wedge to serve"
            ),
            calories = 460, proteinGrams = 20.0, carbGrams = 78.0, fatGrams = 6.0, fiberGrams = 12.0,
            prepMinutes = 5, cookMinutes = 25,
            instructions = listOf(
                "Heat oil; add cumin seeds, let them splutter, then add garlic.",
                "Add turmeric, lentils, rice, and broth.",
                "Bring to a boil, cover, and simmer on low 20 minutes until soft.",
                "Season well; serve with lemon wedge."
            ),
            storageNotes = "Refrigerates up to 4 days; add a splash of water when reheating.",
            metabolicResetScore = 7,
            antiInflammatoryScore = 8,
            insulinResistanceScore = 6,
            womensHealthScore = 7,
            glucoseImpactScore = 5
        ),

        Recipe(
            id = "methi_dal",
            name = "Methi Dal (Fenugreek Lentil Curry)",
            description = "Red lentils cooked with fresh fenugreek leaves, a traditional ingredient in Ayurveda known to support blood sugar regulation. A dish used in metabolic reset protocols for generations.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein", "Whole Foods"),
            proteinSource = "Lentils",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "½ cup red lentils (rinsed)",
                "1 cup fresh fenugreek leaves (methi, roughly chopped)",
                "1 medium tomato (diced)",
                "½ onion (diced)",
                "2 garlic cloves (minced)",
                "1 tsp cumin seeds",
                "½ tsp turmeric",
                "½ tsp coriander powder",
                "1 tbsp olive oil",
                "Salt to taste"
            ),
            calories = 370, proteinGrams = 20.0, carbGrams = 50.0, fatGrams = 8.0, fiberGrams = 13.0,
            prepMinutes = 10, cookMinutes = 25,
            instructions = listOf(
                "Cook lentils in 2 cups water with turmeric until soft, about 15 minutes.",
                "Heat oil; sauté cumin seeds, then onion until golden.",
                "Add garlic, tomato, and coriander; cook until tomatoes break down.",
                "Add methi leaves and cook 3 minutes.",
                "Combine with cooked lentils; simmer together 5 minutes. Season and serve."
            ),
            metabolicResetScore = 9,
            antiInflammatoryScore = 7,
            insulinResistanceScore = 8,
            womensHealthScore = 7,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "soya_keema",
            name = "Soya Keema Masala",
            description = "Minced soya (textured vegetable protein) cooked like keema with green peas, tomatoes, and whole spices. Among the highest plant-protein dinners in this library.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Soy",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "1 cup soya mince (TVP, rehydrated)",
                "½ cup green peas",
                "1 medium onion (finely diced)",
                "1 can diced tomatoes",
                "2 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "1 tsp cumin",
                "1 tsp coriander powder",
                "½ tsp garam masala",
                "1 tbsp olive oil",
                "Salt to taste"
            ),
            calories = 400, proteinGrams = 40.0, carbGrams = 30.0, fatGrams = 10.0, fiberGrams = 10.0,
            prepMinutes = 10, cookMinutes = 20,
            instructions = listOf(
                "Rehydrate soya mince in hot water 10 minutes; squeeze out moisture.",
                "Heat oil; sauté onion 5 minutes until golden.",
                "Add garlic, ginger, cumin, and coriander; cook 2 minutes.",
                "Add tomatoes and cook until sauce thickens.",
                "Add soya mince and peas; simmer 10 minutes. Finish with garam masala."
            ),
            storageNotes = "Refrigerates for 3 days; great in wraps next day.",
            metabolicResetScore = 8,
            antiInflammatoryScore = 5,
            insulinResistanceScore = 7,
            womensHealthScore = 6,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "tofu_palak",
            name = "Palak Tofu (Spinach & Tofu Curry)",
            description = "Firm tofu simmered in a velvety spiced spinach gravy. Spinach provides iron and folate; tofu and turmeric deliver a potent anti-inflammatory combination.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Tofu",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "200g firm tofu (cubed)",
                "3 cups fresh spinach (blanched)",
                "1 medium onion (chopped)",
                "1 medium tomato (chopped)",
                "2 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "½ tsp turmeric",
                "½ tsp cumin",
                "½ tsp garam masala",
                "1 tbsp olive oil",
                "Salt to taste"
            ),
            calories = 340, proteinGrams = 22.0, carbGrams = 20.0, fatGrams = 18.0, fiberGrams = 6.0,
            prepMinutes = 10, cookMinutes = 20,
            instructions = listOf(
                "Pan-fry tofu in 1 tsp oil until golden; set aside.",
                "Blend blanched spinach to a smooth purée.",
                "Heat remaining oil; sauté onion, garlic, and ginger 5 minutes.",
                "Add cumin, turmeric, tomato; cook until soft.",
                "Add spinach purée; simmer 5 minutes. Add tofu and garam masala; heat through."
            ),
            metabolicResetScore = 5,
            antiInflammatoryScore = 9,
            insulinResistanceScore = 7,
            womensHealthScore = 8,
            glucoseImpactScore = 2
        ),

        Recipe(
            id = "broccoli_quinoa",
            name = "Roasted Broccoli & Quinoa Power Bowl",
            description = "Caramelised roasted broccoli over fluffy quinoa with a lemon-tahini dressing and hemp seeds. Broccoli's sulforaphane is one of the most potent anti-inflammatory phytonutrients.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein", "Whole Foods"),
            proteinSource = "Seeds",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "2 cups broccoli florets",
                "½ cup dry quinoa (cooked)",
                "2 tbsp tahini",
                "1 tbsp lemon juice",
                "1 garlic clove (minced)",
                "2 tbsp hemp seeds",
                "1 tbsp olive oil",
                "½ tsp chilli flakes",
                "Salt to taste"
            ),
            calories = 460, proteinGrams = 24.0, carbGrams = 50.0, fatGrams = 20.0, fiberGrams = 10.0,
            prepMinutes = 10, cookMinutes = 25,
            instructions = listOf(
                "Toss broccoli with olive oil, chilli flakes, and salt; roast at 200°C for 20–25 minutes until crispy at edges.",
                "Cook quinoa in 1 cup water until fluffy.",
                "Whisk tahini, lemon juice, garlic, and 2 tbsp water to a smooth dressing.",
                "Plate quinoa and broccoli; drizzle dressing and scatter hemp seeds."
            ),
            metabolicResetScore = 5,
            antiInflammatoryScore = 9,
            insulinResistanceScore = 7,
            womensHealthScore = 7,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "kitchari",
            name = "Kitchari (Mung Bean & Rice Cleanse Bowl)",
            description = "The Ayurvedic healing bowl — split mung dal and basmati rice cooked together with turmeric, cumin, and a touch of ghee. Deeply nourishing, easy to digest, and restorative.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "Whole Foods"),
            proteinSource = "Lentils",
            restrictions = listOf("Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset", "Anti-Inflammatory"),
            ingredients = listOf(
                "½ cup split yellow mung dal",
                "¼ cup basmati rice",
                "1 tsp cumin seeds",
                "½ tsp turmeric",
                "½ tsp coriander powder",
                "1 tsp fresh ginger (grated)",
                "1 tbsp ghee",
                "3 cups water",
                "Salt to taste",
                "Fresh coriander to garnish"
            ),
            calories = 390, proteinGrams = 18.0, carbGrams = 64.0, fatGrams = 8.0, fiberGrams = 10.0,
            prepMinutes = 5, cookMinutes = 30,
            instructions = listOf(
                "Heat ghee in a pot; add cumin seeds and let them splutter.",
                "Add ginger, turmeric, and coriander; stir 30 seconds.",
                "Add rinsed mung dal, rice, and water; bring to a boil.",
                "Reduce to low, cover, and cook 25–30 minutes until soft and porridge-like.",
                "Season with salt; garnish with coriander."
            ),
            storageNotes = "Best eaten fresh; thickens as it sits — add water when reheating.",
            metabolicResetScore = 8,
            antiInflammatoryScore = 8,
            insulinResistanceScore = 6,
            womensHealthScore = 7,
            glucoseImpactScore = 5
        ),

        Recipe(
            id = "walnut_mushroom_bowl",
            name = "Walnut & Portobello Mushroom Brown Rice Bowl",
            description = "Meaty portobello mushrooms and crunchy walnuts over brown rice in a tamari-thyme sauce. Walnuts are the richest nut source of anti-inflammatory omega-3 ALA.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Nuts",
            restrictions = listOf("Dairy Free", "Gluten Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "2 large portobello mushrooms (sliced)",
                "½ cup cooked brown rice",
                "3 tbsp walnuts (roughly chopped)",
                "2 garlic cloves (minced)",
                "1 tbsp low-sodium tamari",
                "1 tbsp olive oil",
                "1 tsp fresh thyme",
                "1 cup baby spinach",
                "Salt and pepper to taste"
            ),
            calories = 460, proteinGrams = 16.0, carbGrams = 54.0, fatGrams = 22.0, fiberGrams = 8.0,
            prepMinutes = 10, cookMinutes = 15,
            instructions = listOf(
                "Sauté garlic in olive oil 1 minute; add mushrooms and cook until golden.",
                "Add tamari and thyme; cook 3 more minutes.",
                "Toss in walnuts; stir 1 minute.",
                "Serve over brown rice with a bed of baby spinach."
            ),
            metabolicResetScore = 4,
            antiInflammatoryScore = 9,
            insulinResistanceScore = 5,
            womensHealthScore = 7,
            glucoseImpactScore = 5
        ),

        Recipe(
            id = "paneer_tikka_wrap",
            name = "Paneer Tikka Whole-Wheat Wrap",
            description = "Charred paneer tikka with crisp vegetables and cooling mint-coriander chutney in a whole-wheat roti. A satisfying high-protein dinner that fits within a metabolic reset plan.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Paneer",
            restrictions = listOf("Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "200g paneer (cubed)",
                "½ cup low-fat yogurt",
                "1 tsp tikka masala",
                "½ tsp turmeric",
                "½ tsp cumin",
                "2 whole-wheat rotis",
                "½ cup red onion (sliced)",
                "½ cup cucumber (sliced)",
                "2 tbsp mint-coriander chutney",
                "1 tsp lemon juice"
            ),
            calories = 540, proteinGrams = 34.0, carbGrams = 50.0, fatGrams = 20.0, fiberGrams = 6.0,
            prepMinutes = 15, cookMinutes = 15,
            instructions = listOf(
                "Marinate paneer in yogurt, tikka masala, turmeric, cumin, and lemon juice for 10 minutes.",
                "Grill or pan-sear paneer on high heat until charred at edges, about 4 minutes per side.",
                "Warm rotis; spread chutney over each.",
                "Layer with onion, cucumber, and paneer tikka; roll and serve."
            ),
            metabolicResetScore = 8,
            antiInflammatoryScore = 4,
            insulinResistanceScore = 6,
            womensHealthScore = 7,
            glucoseImpactScore = 5
        ),

        Recipe(
            id = "omega_tofu_bowl",
            name = "Omega-3 Chia-Crusted Tofu Bowl",
            description = "Tofu encrusted in chia seeds for a crunchy omega-3 shell, served over quinoa with avocado and lemon tahini. A powerhouse of anti-inflammatory fats.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Tofu",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "200g extra-firm tofu (sliced)",
                "3 tbsp chia seeds",
                "½ cup dry quinoa (cooked)",
                "½ ripe avocado (sliced)",
                "2 tbsp tahini",
                "1 tbsp lemon juice",
                "1 cup baby spinach",
                "1 tsp olive oil",
                "Salt to taste"
            ),
            calories = 530, proteinGrams = 28.0, carbGrams = 44.0, fatGrams = 28.0, fiberGrams = 16.0,
            prepMinutes = 10, cookMinutes = 15,
            instructions = listOf(
                "Press tofu; coat each slice with chia seeds, pressing firmly.",
                "Pan-fry in olive oil over medium heat 4–5 minutes per side until golden and crisp.",
                "Cook quinoa; whisk tahini with lemon juice and 2 tbsp water.",
                "Plate spinach, quinoa, avocado, and tofu; drizzle with tahini dressing."
            ),
            metabolicResetScore = 5,
            antiInflammatoryScore = 10,
            insulinResistanceScore = 7,
            womensHealthScore = 8,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "rajma_chawal",
            name = "Light Rajma Chawal",
            description = "The beloved North Indian comfort dish made lighter — red kidney beans in a tomato-onion masala served over brown basmati rice. High in plant protein and dietary fiber.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein", "Whole Foods"),
            proteinSource = "Lentils",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "1 cup cooked red kidney beans",
                "1 medium onion (diced)",
                "1 can diced tomatoes",
                "2 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "1 tsp rajma masala",
                "½ tsp cumin seeds",
                "½ cup cooked brown basmati rice",
                "1 tbsp olive oil",
                "Salt and coriander to garnish"
            ),
            calories = 470, proteinGrams = 20.0, carbGrams = 78.0, fatGrams = 6.0, fiberGrams = 15.0,
            prepMinutes = 10, cookMinutes = 20,
            instructions = listOf(
                "Heat oil; add cumin seeds, then onion and cook until golden.",
                "Add garlic and ginger; cook 2 minutes.",
                "Add tomatoes and rajma masala; simmer until thick.",
                "Add kidney beans; cook 10 minutes on low until flavours meld.",
                "Serve over brown rice; garnish with coriander."
            ),
            metabolicResetScore = 8,
            antiInflammatoryScore = 6,
            insulinResistanceScore = 6,
            womensHealthScore = 7,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "ginger_veggie_soup",
            name = "Ginger Turmeric Healing Vegetable Soup",
            description = "A light, mineral-rich soup with ginger, turmeric, and seasonal vegetables. Black pepper enhances curcumin absorption by 2000% — a detail most people miss.",
            mealType = "Dinner",
            tags = listOf("Vegan", "Whole Foods"),
            proteinSource = "Lentils",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "1 cup carrot (sliced)",
                "1 cup zucchini (cubed)",
                "1 cup spinach",
                "½ cup red lentils",
                "3 cups vegetable broth",
                "1 tsp turmeric",
                "1 tsp fresh ginger (grated)",
                "2 garlic cloves (minced)",
                "Juice of ½ lemon",
                "Freshly cracked black pepper",
                "1 tbsp olive oil"
            ),
            calories = 260, proteinGrams = 14.0, carbGrams = 36.0, fatGrams = 6.0, fiberGrams = 10.0,
            prepMinutes = 10, cookMinutes = 25,
            instructions = listOf(
                "Heat oil in a large pot; sauté garlic and ginger 2 minutes.",
                "Add turmeric, carrots, and lentils; stir 1 minute.",
                "Add broth and zucchini; bring to a boil.",
                "Simmer 20 minutes; add spinach in last 2 minutes.",
                "Finish with lemon juice and generous black pepper."
            ),
            storageNotes = "Freezes well for up to 1 month.",
            metabolicResetScore = 5,
            antiInflammatoryScore = 10,
            insulinResistanceScore = 8,
            womensHealthScore = 7,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "paneer_sheet_pan",
            name = "Sheet-Pan Paneer & Roasted Vegetables",
            description = "One-pan dinner with herb-marinated paneer and colourful roasted vegetables. Minimal cleanup, maximum protein, and a satisfying variety of textures.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Paneer",
            restrictions = listOf("Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "200g paneer (cubed)",
                "1 bell pepper (sliced)",
                "1 zucchini (sliced)",
                "1 cup cherry tomatoes",
                "1 tbsp olive oil",
                "1 tsp Italian herbs",
                "½ tsp garlic powder",
                "½ tsp smoked paprika",
                "Salt and pepper to taste",
                "1 tbsp fresh basil to garnish"
            ),
            calories = 470, proteinGrams = 30.0, carbGrams = 18.0, fatGrams = 32.0, fiberGrams = 5.0,
            prepMinutes = 10, cookMinutes = 25,
            instructions = listOf(
                "Preheat oven to 200°C (400°F).",
                "Toss paneer and vegetables with olive oil, herbs, garlic powder, paprika, salt, and pepper.",
                "Spread on a baking sheet in a single layer.",
                "Roast 20–25 minutes until paneer is golden and vegetables are caramelised.",
                "Garnish with fresh basil."
            ),
            metabolicResetScore = 8,
            antiInflammatoryScore = 6,
            insulinResistanceScore = 7,
            womensHealthScore = 7,
            glucoseImpactScore = 2
        ),

        Recipe(
            id = "paneer_tikka_masala",
            name = "High-Protein Paneer Tikka Masala",
            description = "The restaurant favourite made at home with a generous 250g of paneer. The larger paneer serving pushes this classic to 40g of protein — the highest-protein vegetarian curry in the catalog.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Paneer",
            restrictions = listOf("Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "250g paneer (cubed)",
                "½ cup low-fat yogurt",
                "1 tsp tikka masala",
                "1 can diced tomatoes",
                "1 medium onion (diced)",
                "2 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "½ tsp cumin",
                "½ tsp turmeric",
                "½ tsp garam masala",
                "1 tbsp olive oil",
                "Salt and fresh coriander to garnish"
            ),
            calories = 540, proteinGrams = 40.0, carbGrams = 24.0, fatGrams = 32.0, fiberGrams = 5.0,
            prepMinutes = 10, cookMinutes = 20,
            instructions = listOf(
                "Marinate paneer in yogurt, tikka masala, turmeric, and a pinch of salt for 10 minutes.",
                "Grill or pan-sear paneer until charred at edges; set aside.",
                "Heat oil; sauté onion 5 minutes, add garlic, ginger, and cumin.",
                "Add tomatoes and simmer 10 minutes until sauce thickens.",
                "Add paneer, garam masala; simmer 5 minutes. Garnish with coriander."
            ),
            metabolicResetScore = 8,
            antiInflammatoryScore = 5,
            insulinResistanceScore = 7,
            womensHealthScore = 7,
            glucoseImpactScore = 2
        ),

        Recipe(
            id = "soy_chunk_palak_curry",
            name = "High-Protein Soy Chunk Palak Curry",
            description = "80g of dry soy chunks simmered in a velvety spiced spinach purée. This vegan twist on palak paneer delivers 44g of protein — the highest-protein vegan dinner in the catalog — with a fraction of the fat.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Soy",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "80g soy chunks (dry weight)",
                "3 cups fresh spinach (blanched)",
                "1 medium onion (chopped)",
                "1 medium tomato (chopped)",
                "2 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "½ tsp turmeric",
                "½ tsp cumin",
                "½ tsp garam masala",
                "1 tbsp olive oil",
                "Salt to taste"
            ),
            calories = 420, proteinGrams = 44.0, carbGrams = 24.0, fatGrams = 10.0, fiberGrams = 12.0,
            prepMinutes = 15, cookMinutes = 20,
            instructions = listOf(
                "Soak soy chunks in boiling water 10 minutes; drain and squeeze dry.",
                "Blend blanched spinach to a smooth purée.",
                "Heat oil; sauté onion, garlic, and ginger 5 minutes.",
                "Add cumin, turmeric, and tomato; cook until soft.",
                "Add spinach purée; simmer 5 minutes. Add soy chunks and garam masala; simmer 8 minutes more."
            ),
            metabolicResetScore = 6,
            antiInflammatoryScore = 9,
            insulinResistanceScore = 7,
            womensHealthScore = 8,
            glucoseImpactScore = 2
        ),

        Recipe(
            id = "tempeh_coconut_curry",
            name = "Tempeh Coconut Curry",
            description = "200g of tempeh simmered in a fragrant Thai-inspired coconut broth with lemongrass and red curry paste. Tempeh's dense protein structure holds up to long simmering, absorbing the curry flavour through every bite.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Soy",
            restrictions = listOf("Dairy Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "200g tempeh (cubed)",
                "1 can light coconut milk",
                "1 cup vegetable broth",
                "1 lemongrass stalk (bruised)",
                "1 tbsp red curry paste",
                "2 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "1 cup broccoli florets",
                "1 red bell pepper (sliced)",
                "1 tbsp low-sodium soy sauce",
                "1 tsp lime juice"
            ),
            calories = 490, proteinGrams = 40.0, carbGrams = 28.0, fatGrams = 26.0, fiberGrams = 8.0,
            prepMinutes = 10, cookMinutes = 20,
            instructions = listOf(
                "Pan-fry tempeh cubes in a dry pan until golden; set aside.",
                "In the same pan, sauté garlic, ginger, and curry paste 2 minutes.",
                "Add coconut milk, broth, and lemongrass; bring to a gentle simmer.",
                "Add broccoli and bell pepper; simmer 5 minutes.",
                "Add tempeh and soy sauce; simmer 5 more minutes. Finish with lime juice."
            ),
            metabolicResetScore = 5,
            antiInflammatoryScore = 8,
            insulinResistanceScore = 6,
            womensHealthScore = 6,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "paneer_egg_masala",
            name = "Paneer & Egg Masala Curry",
            description = "Boiled eggs added to a paneer curry is a classical North Indian approach to maximising protein in a single pot. Two proteins, two textures — tender paneer and firm egg — in a rich tomato-onion masala.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Paneer",
            restrictions = listOf("Gluten Free", "Nut Free", "Soy Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "200g paneer (cubed)",
                "3 hard-boiled eggs (halved)",
                "1 can diced tomatoes",
                "1 medium onion (diced)",
                "2 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "1 tsp cumin",
                "1 tsp coriander powder",
                "½ tsp turmeric",
                "½ tsp garam masala",
                "1 tbsp olive oil",
                "Salt and fresh coriander to garnish"
            ),
            calories = 520, proteinGrams = 42.0, carbGrams = 18.0, fatGrams = 32.0, fiberGrams = 5.0,
            prepMinutes = 10, cookMinutes = 20,
            instructions = listOf(
                "Pan-sear paneer cubes until golden; set aside.",
                "Heat oil; sauté onion 5 minutes, add garlic, ginger, cumin, coriander, and turmeric.",
                "Add tomatoes; simmer 10 minutes until thick.",
                "Add paneer and halved eggs; simmer gently 5 minutes.",
                "Finish with garam masala and coriander."
            ),
            metabolicResetScore = 9,
            antiInflammatoryScore = 5,
            insulinResistanceScore = 7,
            womensHealthScore = 7,
            glucoseImpactScore = 2
        ),

        Recipe(
            id = "tofu_edamame_stir_fry",
            name = "Crispy Tofu & Edamame Stir-Fry",
            description = "Double soy protein: crispy pan-fried tofu meets warm edamame in a ginger-garlic soy glaze over brown rice. Two complete soy proteins stacked in one bowl for 42g without any animal products.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Tofu",
            restrictions = listOf("Dairy Free", "Egg Free"),
            collection = listOf("Anti-Inflammatory"),
            ingredients = listOf(
                "200g firm tofu (pressed, cubed)",
                "1½ cups shelled edamame (cooked)",
                "½ cup cooked brown rice",
                "2 cups broccoli florets",
                "3 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "2 tbsp low-sodium soy sauce",
                "1 tsp sesame oil",
                "1 tsp cornstarch",
                "1 tsp sesame seeds"
            ),
            calories = 470, proteinGrams = 42.0, carbGrams = 44.0, fatGrams = 14.0, fiberGrams = 10.0,
            prepMinutes = 15, cookMinutes = 15,
            instructions = listOf(
                "Toss tofu with cornstarch; pan-fry in sesame oil over high heat until golden, about 5 minutes.",
                "Add garlic and ginger; stir 1 minute.",
                "Add broccoli; stir-fry 4 minutes.",
                "Add edamame and soy sauce; toss to coat.",
                "Serve over brown rice; garnish with sesame seeds."
            ),
            metabolicResetScore = 5,
            antiInflammatoryScore = 8,
            insulinResistanceScore = 6,
            womensHealthScore = 7,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "high_protein_soya_biryani",
            name = "High-Protein Soya Biryani",
            description = "The highest-protein dinner in the catalog: 100g of dry textured soy protein layered with fragrant basmati rice and whole spices. This biryani delivers 50g of protein — the ceiling this catalog was designed to reach.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Soy",
            restrictions = listOf("Dairy Free", "Gluten Free", "Nut Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "100g textured soy protein (soy chunks, minced or small)",
                "½ cup basmati rice",
                "1 large onion (thinly sliced)",
                "1 tsp cumin seeds",
                "2 bay leaves",
                "4 cardamom pods",
                "1 cinnamon stick",
                "1 tsp fresh ginger (grated)",
                "2 garlic cloves (minced)",
                "½ tsp turmeric",
                "1 tsp biryani masala",
                "1 tbsp olive oil",
                "Salt and fresh coriander to garnish"
            ),
            calories = 560, proteinGrams = 50.0, carbGrams = 60.0, fatGrams = 10.0, fiberGrams = 12.0,
            prepMinutes = 15, cookMinutes = 30,
            instructions = listOf(
                "Soak soy protein in boiling water 10 minutes; drain and squeeze dry.",
                "Heat oil in a heavy pot; fry onion until golden-brown, about 10 minutes. Set half aside for garnish.",
                "Add cumin, bay leaves, cardamom, cinnamon, garlic, ginger, and biryani masala; stir 2 minutes.",
                "Add soy protein and turmeric; cook 5 minutes.",
                "Add rice and 1 cup water; bring to a boil, cover tightly, and cook on low 15 minutes.",
                "Fluff gently; garnish with reserved onions and coriander."
            ),
            storageNotes = "Refrigerates up to 3 days; add a splash of water when reheating.",
            metabolicResetScore = 8,
            antiInflammatoryScore = 4,
            insulinResistanceScore = 6,
            womensHealthScore = 6,
            glucoseImpactScore = 5
        ),

        Recipe(
            id = "tempeh_black_bean_bowl",
            name = "Tempeh & Black Bean Dinner Bowl",
            description = "Tempeh and black beans supply protein from different biological pathways — combined, they hit 46g with a complementary amino acid profile. Smoky cumin-lime seasoning ties this Latin-fusion dinner together.",
            mealType = "Dinner",
            tags = listOf("Vegan", "High Protein"),
            proteinSource = "Soy",
            restrictions = listOf("Dairy Free", "Gluten Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "200g tempeh (cubed)",
                "½ cup cooked black beans",
                "½ cup cooked brown rice",
                "1 cup cherry tomatoes (halved)",
                "1 cup baby spinach",
                "1 tsp cumin",
                "1 tsp smoked paprika",
                "1 tbsp tamari",
                "1 tsp olive oil",
                "Juice of ½ lime",
                "Fresh coriander to garnish"
            ),
            calories = 510, proteinGrams = 46.0, carbGrams = 46.0, fatGrams = 18.0, fiberGrams = 12.0,
            prepMinutes = 10, cookMinutes = 15,
            instructions = listOf(
                "Toss tempeh with cumin, paprika, and tamari; pan-fry in olive oil 4–5 minutes per side.",
                "Warm black beans; season with salt.",
                "Build bowl: brown rice, spinach, tomatoes, beans, tempeh.",
                "Drizzle lime juice and garnish with coriander."
            ),
            metabolicResetScore = 8,
            antiInflammatoryScore = 6,
            insulinResistanceScore = 6,
            womensHealthScore = 6,
            glucoseImpactScore = 4
        ),

        Recipe(
            id = "paneer_dal_makhani",
            name = "Protein-Boosted Dal Makhani with Paneer",
            description = "Dal makhani — the slow-cooked black lentil and kidney bean dal — enriched with cubes of pan-seared paneer. Three protein sources in one pot: black lentils, kidney beans, and dairy protein from paneer, for 42g total.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Paneer",
            restrictions = listOf("Gluten Free", "Nut Free", "Soy Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "150g paneer (cubed, pan-seared)",
                "½ cup whole black lentils (urad dal, soaked overnight)",
                "¼ cup red kidney beans (cooked)",
                "1 can diced tomatoes",
                "1 medium onion (diced)",
                "2 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "1 tsp cumin seeds",
                "½ tsp garam masala",
                "1 tbsp olive oil",
                "Salt and coriander to garnish"
            ),
            calories = 530, proteinGrams = 42.0, carbGrams = 50.0, fatGrams = 18.0, fiberGrams = 14.0,
            prepMinutes = 15, cookMinutes = 35,
            instructions = listOf(
                "Pressure-cook soaked black lentils and kidney beans until tender, about 20 minutes.",
                "Pan-sear paneer until golden; set aside.",
                "In a separate pan, heat olive oil; add cumin seeds, then onion, garlic, and ginger.",
                "Add tomatoes and cook until thick; stir into cooked dal.",
                "Simmer dal 10 minutes; add paneer and garam masala; heat through."
            ),
            storageNotes = "Refrigerates 4 days; freezes well.",
            metabolicResetScore = 8,
            antiInflammatoryScore = 6,
            insulinResistanceScore = 7,
            womensHealthScore = 8,
            glucoseImpactScore = 3
        ),

        Recipe(
            id = "soy_paneer_double_curry",
            name = "Double-Protein Soy Chunk & Paneer Curry",
            description = "Soy chunks and paneer combined in one masala for 48g of protein per serving — designed specifically for days when the protein target feels unreachable. Two complementary sources; one simple curry.",
            mealType = "Dinner",
            tags = listOf("Vegetarian", "High Protein"),
            proteinSource = "Paneer",
            restrictions = listOf("Gluten Free", "Nut Free", "Egg Free"),
            collection = listOf("Metabolic Reset"),
            ingredients = listOf(
                "150g paneer (cubed)",
                "50g soy chunks (dry weight)",
                "1 can diced tomatoes",
                "1 medium onion (diced)",
                "2 garlic cloves (minced)",
                "1 tsp fresh ginger (grated)",
                "1 tsp cumin",
                "1 tsp coriander powder",
                "½ tsp turmeric",
                "½ tsp garam masala",
                "1 tbsp olive oil",
                "Salt and fresh coriander to garnish"
            ),
            calories = 530, proteinGrams = 48.0, carbGrams = 26.0, fatGrams = 24.0, fiberGrams = 8.0,
            prepMinutes = 15, cookMinutes = 22,
            instructions = listOf(
                "Soak soy chunks in boiling water 10 minutes; drain and squeeze dry.",
                "Pan-sear paneer until golden; set aside.",
                "Heat oil; sauté onion 5 minutes, add garlic, ginger, cumin, coriander, and turmeric.",
                "Add tomatoes and simmer 8 minutes until thick.",
                "Add soy chunks; simmer 8 minutes. Add paneer and garam masala; heat through."
            ),
            metabolicResetScore = 9,
            antiInflammatoryScore = 5,
            insulinResistanceScore = 7,
            womensHealthScore = 7,
            glucoseImpactScore = 2
        ),
    )
}
